name: campuscravings
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  intl: ^0.18.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  custom_info_window: ^1.0.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets: 
    - assets/
  uses-material-design: true
  fonts:
     - family: Blockletter
       fonts:
         - asset: fonts/Blockletter.otf
     - family: DM Sans
       fonts:
         - asset: fonts/DMSans.ttf
